### ISSUE TITLE
关于训练的时候遇到的问题

### ISSUE THREAD

**Issue by Hesene** [xuyuan/x-force#3]
**感谢您的分享，我在训练的过程中遇到了一些问题，请您看下：**
`loading annotations into memory...
Done (t=0.15s)
creating index...
index created!
loading annotations into memory...
Done (t=0.14s)
creating index...
index created!
loading annotations into memory...
Done (t=0.16s)
creating index...
index created!
nn.create(model=unet2_e_simple, basenet=senet154)

apex_opt_level: O2
basenet: senet154
batch_size: 16
checkpoints_interval: 20
clip_grad_norm: 0
comment: ''
data_fold: 0
data_norm: false
data_normal: 0.3
data_pseudolabel_images: null
data_pseudolabel_images2: null
data_pseudolabel_labels: null
data_pseudolabel_labels2: null
data_pseudolabel_rate: 0
data_root: /home/vip415/HJH/x-force-unet/data/jinnan2_round2_train_20190401
device: auto
gradient_accumulation: 1
image_size: 128
jobs: 4
learning_rate: 0.01
local_rank: null
log_dir: /data/train_2019.06.16.21-22-52
log_images: false
log_loss_interval: 0
loss: bce
lr_scheduler: noam
lr_scheduler_gamma: 0.1
lr_scheduler_milestones: [60, 80]
lr_scheduler_patience: 20
lr_scheduler_step_size: 40
lr_scheduler_warmup: 10
max_epochs: 1000
mixup: -1
model: ''
momentum: 0.9
no_bn_wd: false
no_mixup_epochs: 0.1
optim: sgd
resume: null
resume_checkpoint_file: null
stopping_learning_rate: 1.0e-09
sync_bn: false
test_image_size: 0
validation_interval: 5
version: unet2_e_simple
weight_decay: 0.0005
weights: null
write_graph: false

use cuda
Selected optimization level O2:  FP16 training with FP32 batchnorm and FP32 master weights.

Defaults for this optimization level are:
enabled                : True
opt_level              : O2
cast_model_type        : torch.float16
patch_torch_functions  : False
keep_batchnorm_fp32    : True
master_weights         : True
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O2
cast_model_type        : torch.float16
patch_torch_functions  : False
keep_batchnorm_fp32    : True
master_weights         : True
loss_scale             : dynamic
Traceback (most recent call last):
  File "/home/vip415/anaconda3/envs/py36_mmdetV0/lib/python3.6/pathlib.py", line 1226, in mkdir
    self._accessor.mkdir(self, mode)
  File "/home/vip415/anaconda3/envs/py36_mmdetV0/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/data/train_2019.06.16.21-22-52/checkpoints'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cc/anaconda3/envs/py36_mmdetV0/lib/python3.6/pathlib.py", line 1226, in mkdir
    self._accessor.mkdir(self, mode)
  File "/home/cc/anaconda3/envs/py36_mmdetV0/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/data/train_2019.06.16.21-22-52'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 235, in <module>
    trainer = IoUTrainer(model, datasets_t, the_criterion, args)
  File "/home/cc/ccx/x-force-unet/code/unet/trainer/train.py", line 293, in __init__
    self.checkpoints_folder.mkdir(parents=True, exist_ok=True)
  File "/home/cc/anaconda3/envs/py36_mmdetV0/lib/python3.6/pathlib.py", line 1230, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/home/cc/anaconda3/envs/py36_mmdetV0/lib/python3.6/pathlib.py", line 1230, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/home/cc/anaconda3/envs/py36_mmdetV0/lib/python3.6/pathlib.py", line 1226, in mkdir
    self._accessor.mkdir(self, mode)
  File "/home/cc/anaconda3/envs/py36_mmdetV0/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
PermissionError: [Errno 13] Permission denied: '/data'`
**我尝试赋予train.py和/home/cc/anaconda3/envs/py36_mmdetV0/lib/python3.6/pathlib.py文件夹777权限，但是还是没能解决，我的数据集放在/home/cc/ccx/x-force-unet/data路径下？
感谢您的阅读与解答。**

**Comment by xuyuan** [comment]
请仔细看输出
```
FileNotFoundError: [Errno 2] No such file or directory: '/data/train_2019.06.16.21-22-52'
```

这是log和模型输出的目录，/data 是因为脚本是按照比赛方的虚拟机设置的，请修改 `train.sh` 中的`TRAIN_LOG_DIR`

**Comment by Hesene** [comment]
您好，我将
`TRAIN_LOG_DIR="/data/train_${TIME}"`
改为
`TRAIN_LOG_DIR="/home/cc/ccx/x-force-unet/data/train_${TIME}"`
但是出现了以下的错误
logging into home/cc/ccx/x-force-unet/data/
Traceback (most recent call last):
  File "train.py", line 235, in <module>
    trainer = IoUTrainer(model, datasets_t, the_criterion, args)
  File "/home/cc/HJH/x-force-unet/code/unet/trainer/train.py", line 303, in __init__
    self.tb_writer = SummaryWriter(log_dir=str(log_dir))
  File "/home/cc/anaconda3/envs/py36_mmdetV0/lib/python3.6/site-packages/tensorboardX/writer.py", line 254, in __init__
    self._get_file_writer()
  File "/home/cc/anaconda3/envs/py36_mmdetV0/lib/python3.6/site-packages/tensorboardX/writer.py", line 310, in _get_file_writer
    self.file_writer = FileWriter(logdir=self.logdir, **self.kwargs)
TypeError: __init__() got an unexpected keyword argument 'log_dir'
/home/cc/ccx/x-force-unet/data/路径是存在的，请问是不可以使用绝对路径吗？

**Comment by Hesene** [comment]
您好，请问能否告知您训练的时候的cuda版本与pytorch版本呢？感谢

**Comment by Hesene** [comment]
**您好，很抱歉再次打扰您，我在解决完前面的问题之后。出现了cuda报错，我尝试更换了cuda9.0和cuda10.0，以及torch1.0,0、torch1.0,1但是这个错误始终存在，我尝试谷歌解决，但是依旧没有找到好的解决方法，希望能从您这里得到一些解决方案。或者您使用该代码的时候的cuda版本torch版本，感谢您的分享与回复**

..........
  (fuse): Sequential(
    (0): Dropout2d(p=0, inplace)
    (1): Conv2d(256, 160, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (2): ABN(160, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True, activation=leaky_relu, slope=0.01)
  )
  (logit): Conv2d(160, 5, kernel_size=(1, 1), stride=(1, 1), bias=False)
  (logit_edge): Conv2d(160, 5, kernel_size=(1, 1), stride=(1, 1), bias=False)
) Epochs: 0 / 1000
  0%|                                                                                         | 0/1000 [00:00<?, ?epoch/s/home/cc/anaconda3/envs/py36_unet/lib/python3.6/site-packages/torch/nn/modules/upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=405 error=11 : invalid argument
Traceback (most recent call last):
  File "train.py", line 236, in <module>
    trainer.run()
  File "/home/cc/ccx/x-force-unet/code/unet/trainer/train.py", line 499, in run
    epoch_loss = self.run_epoch(epoch, phase)
  File "/home/cc/ccx/x-force-unet/code/unet/trainer/train.py", line 373, in run_epoch
    outputs = self.net(inputs)
  File "/home/cc/anaconda3/envs/py36_unet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cc/anaconda3/envs/py36_unet/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 143, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/cc/anaconda3/envs/py36_unet/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/cc/anaconda3/envs/py36_unet/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/home/cc/anaconda3/envs/py36_unet/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/home/cc/anaconda3/envs/py36_unet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cc/anaconda3/envs/py36_unet/lib/python3.6/site-packages/apex/amp/_initialize.py", line 204, in new_fwd
    **applier(kwargs, input_caster))
  File "/home/cc/ccx/x-force-unet/code/unet/nn/unet.py", line 336, in forward
    y = UNetBase.forward(self, x)
  File "/home/cc/ccx/x-force-unet/code/unet/nn/unet.py", line 167, in forward
    e1 = self.encoder1(x)#; print('e1', e1.size())
  File "/home/cc/anaconda3/envs/py36_unet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cc/anaconda3/envs/py36_unet/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/cc/anaconda3/envs/py36_unet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cc/anaconda3/envs/py36_unet/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/cc/anaconda3/envs/py36_unet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cc/anaconda3/envs/py36_unet/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:405

**Comment by xuyuan** [comment]
环境设置用conda，配置文件是 https://github.com/xuyuan/x-force/blob/master/code/unet/environment.yml
